/-
Copyright (c) 2026 Benjamin Stanley Frohman. Released under Apache-2.0.
Authors: Benjamin Stanley Frohman (@BenFrohman)
-/

/-!
# Noether–Lefschetz as a named sentence

This is not the Hodge conjecture. It is the statement that a very general
high-degree hypersurface has no extra Hodge classes.
-/

namespace NoetherLefschetz

/-- Placeholder host. Not a scheme. -/
axiom HypersurfaceFourfold : Type

/-- Degree of the host. -/
axiom degree : HypersurfaceFourfold → ℕ

/-- Very general in the moduli space (countable complement of proper loci). -/
axiom VeryGeneral : HypersurfaceFourfold → Prop

/-- Hodge lattice of type (2,2) has rank 1, generated by h². -/
axiom HodgeRankOne : HypersurfaceFourfold → Prop

/-- The theorem this repo exists to name. Proof is the literature, not this file. -/
theorem very_general_high_degree_rank_one
    (X : HypersurfaceFourfold) (hd : 6 ≤ degree X) (hvg : VeryGeneral X) :
    HodgeRankOne X := by
  sorry

end NoetherLefschetz
